spring:
  application:
    name: travel-spring-cloud-gateway
  cloud:
    gateway:
      routes:
        - id: httpbin
          uri: https://httpbin.org
          predicates:
            - Path=/httpbin/**
          filters:
            - StripPrefix=1
        - id: vets-service
          uri: http://vets-service:8080
          predicates:
           - Path=/api/vet/**
          filters:
           - StripPrefix=2
        - id: visits-service
          uri: http://visits-service:8080
          predicates:
            - Path=/api/visit/**
          filters:
            - StripPrefix=2
        - id: customers-service
          uri: http://customer-service:8080
          predicates:
            - Path=/api/customer/**
          filters:
            - StripPrefix=2
        - id: httpbin-service
          uri: http://httpbin-service:8080
          predicates:
            - Path=/get/**
logging:
  level:
    org:
      springframework:
        cloud.gateway: DEBUG
        http.server.reactive: DEBUG
        web.reactive: DEBUG

